name: CI_practice
run-name: ${{ github.actor }} is testing out GitHub CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - run: make setup
            - run: make lint
            - name: run tests
              run: make test
